### PR TITLE
Fix #16 -n option: new docker version concatenating container names

### LINKED ISSUE #16: -n option causes metrics-docker-stats.rb to fail
I can run metrics-docker-stats.rb successfully by doing following

```
 /opt/sensu/embedded/bin/ruby ./metrics-docker-stats.rb -H /var/run/docker.sock -p unix 
```

However, when I add "-n" option, it fails with following message.

```
...
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.stats.total_unevictable 0 1449347656
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.stats.unevictable 0 1449347656
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.failcnt 0 1449347656
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.limit 12431413248 1449347656
Check failed to run: 757: unexpected token at 'no such id: portal-apache1mysql
', ["/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "./metrics-docker-stats.rb:113:in `block (3 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:411:in `call_block'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:402:in `<<'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:106:in `read'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:284:in `block in read_body_0'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:269:in `inflater'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'", "./metrics-docker-stats.rb:112:in `block (2 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `catch'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'", "./metrics-docker-stats.rb:111:in `block in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:582:in `start'", "./metrics-docker-stats.rb:109:in `docker_api'", "./metrics-docker-stats.rb:158:in `container_stats'", "./metrics-docker-stats.rb:91:in `block in run'", "./metrics-docker-stats.rb:90:in `each'", "./metrics-docker-stats.rb:90:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

### PR DESCRIPTION
**Pull request by theyough**
## Pull Request Checklist

Fix #16 

#### General

- tested with Docker API version 1.39

### CODE REVIEW

**Comment by majormoses** [comment]
You can ignore that CI failure, I plan on dropping support for all EOL rubies after this PR which should fix it.

File: bin/metrics-docker-stats.rb [hunk 1]
```diff
@@ -160,9 +160,9 @@ def list_containers
 
     containers.each do |container|
       list << if config[:friendly_names]
-                container['Names'][0].delete('/')
+                container['Names'][-1].delete('/')
```
Comment (majormoses) [inline bin/metrics-docker-stats.rb]: should we delete the the `/` or remove everything after the `/`? I think the reason that the `/` was being removed was because its not a valid character according to the [source code](https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/daemon/names/names.go#L5-L6) in a name.

Comment (theyough) [reply bin/metrics-docker-stats.rb]: True, the character is not a valid character.

Comment (theyough) [reply bin/metrics-docker-stats.rb]: in case multiple containers are linked together the container name is concatenate with the other container seperate by `/` .

`./embedded/bin/metrics-docker-stats.rb -n true`

### ACTUAL RESULT

```
Check failed to run: 404 "Not Found", ["/opt/sensu/embedded/lib/ruby/2.4.0/net/http/response.rb:122:in `error!'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-docker-3.1.1/lib/sensu-plugins-docker/client_helpers.rb:41:in `call'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-docker-3.1.1/bin/metrics-docker-stats.rb:175:in `container_stats'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-docker-3.1.1/bin/metrics-docker-stats.rb:122:in `block in run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-docker-3.1.1/bin/metrics-docker-stats.rb:121:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-docker-3.1.1/bin/metrics-docker-stats.rb:121:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.7.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

### EXPECTED RESULT

```
www-prod-do-sgp1-42.docker.container-xxx-prod.name container-xxx-prod 1542816915
```

**Comment by theyough** [comment]
@majormoses, it should be ok. Thanks for the comment

**Comment by majormoses** [comment]
Hey could you please add a changelog entry? https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md#unreleased-change

**Comment by majormoses** [comment]
https://rubygems.org/gems/sensu-plugins-docker/versions/3.2.0
